imports:
    - { resource: config_dev.yml }

liip_functional_test:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
                logging:  false
                profiling: false

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
    firewalls:
        main:
            http_basic: ~

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

monolog:
    use_microseconds: false
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            channels: ['!event', '!doctrine', '!console', '!translation']

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
